// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRpAbj_bVEGoX-V5ktW77U-CCB_ZlkreE',
    appId: '1:1023782043200:web:7faf7f7534252c1cb3a9a5',
    messagingSenderId: '1023782043200',
    projectId: 'greenguardian-4603c',
    authDomain: 'greenguardian-4603c.firebaseapp.com',
    storageBucket: 'greenguardian-4603c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoJr1Rth_uVZ9Nah4ilayHENg396aMTws',
    appId: '1:1023782043200:android:926c4b20543ac8d7b3a9a5',
    messagingSenderId: '1023782043200',
    projectId: 'greenguardian-4603c',
    storageBucket: 'greenguardian-4603c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4dFh2oKXC9LvQnVHkGX_74xPo3sRRVz4',
    appId: '1:1023782043200:ios:999d9d56277d2036b3a9a5',
    messagingSenderId: '1023782043200',
    projectId: 'greenguardian-4603c',
    storageBucket: 'greenguardian-4603c.appspot.com',
    iosBundleId: 'com.example.etrMark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4dFh2oKXC9LvQnVHkGX_74xPo3sRRVz4',
    appId: '1:1023782043200:ios:999d9d56277d2036b3a9a5',
    messagingSenderId: '1023782043200',
    projectId: 'greenguardian-4603c',
    storageBucket: 'greenguardian-4603c.appspot.com',
    iosBundleId: 'com.example.etrMark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRpAbj_bVEGoX-V5ktW77U-CCB_ZlkreE',
    appId: '1:1023782043200:web:455148b36e13ec74b3a9a5',
    messagingSenderId: '1023782043200',
    projectId: 'greenguardian-4603c',
    authDomain: 'greenguardian-4603c.firebaseapp.com',
    storageBucket: 'greenguardian-4603c.appspot.com',
  );
}
